language: r
sudo: false
cache: packages

matrix:
  include:
   - r: release
     os: osx
     before_cache: Rscript -e 'install.packages("pkgdown")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github()'
       skip_cleanup: true
