language: r
sudo: false
cache: packages

matrix:
  include:
   - r: release
     os: osx
     before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github()'
       skip_cleanup: true
