language: r
sudo: false
cache: packages

matrix:
  include:
   - r: release
     os: osx
     latex: false
     fortran: false
     before_install:
        - brew tap theseal/ssh-askpass
        - brew install ssh-askpass
     before_cache: Rscript -e 'install.packages("r-lib/pkgdown")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github()'
       skip_cleanup: true
